// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/rs/zerolog"
	"test-tg/pkg/interfaces"
)

type httpMathematical struct {
	log          zerolog.Logger
	errorHandler ErrorHandler
	svc          *serverMathematical
	base         interfaces.Mathematical
}

func NewMathematical(log zerolog.Logger, svcMathematical interfaces.Mathematical) (srv *httpMathematical) {

	srv = &httpMathematical{
		base: svcMathematical,
		log:  log,
		svc:  newServerMathematical(svcMathematical),
	}
	return
}

func (http httpMathematical) Service() MiddlewareSetMathematical {
	return http.svc
}

func (http *httpMathematical) WithLog(log zerolog.Logger) *httpMathematical {
	http.svc.WithLog(log)
	return http
}

func (http *httpMathematical) WithErrorHandler(handler ErrorHandler) *httpMathematical {
	http.errorHandler = handler
	return http
}

func (http *httpMathematical) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/mathematical", http.serveBatch)
	route.Post("/api/v1/mathematical/add", http.serveAdd)
}
