// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"test-tg/pkg/interfaces"
)

type MathematicalAdd func(ctx context.Context, a int, b int) (result int, err error)

type MiddlewareMathematical func(next interfaces.Mathematical) interfaces.Mathematical

type MiddlewareMathematicalAdd func(next MathematicalAdd) MathematicalAdd
