// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package user

type requestMathematicalAdd struct {
	A int `json:"a"`
	B int `json:"b"`
}

type responseMathematicalAdd struct {
	Result int `json:"result"`
}
